### ISSUE TITLE
Add Route to see all entries of the form

### ISSUE THREAD

**Issue by zJaaal** [zJaaal/grey-dive-challenge#11]
## To-Do

- [x] Add loader for save request
- [x] Add modal for the result of the save request
- [x] Add Review Route to see entries
- [x] Add DataGrid
- [x] Add home button
